Veranstaltungen-Modul (1.23.1): PSR fix
IlchCMS/Ilch-2.0 pull request #1035
Opened 2024-08-15 14:44 UTC by hhunderter

# Description
PSR-Fix

# This PR has been tested in the following browsers:
- [ ] Chrome
- [x] Firefox
- [ ] Opera
- [ ] Edge

2024-08-15 17:09 UTC, blackcoder87 commented on application/modules/events/views/index/navi.php
> +                <li class="nav-item <?php if ($this->getRequest()->getActionName() === 'index') {
Siehe oben. Sieht für mich nicht besser aus.

2024-08-15 17:09 UTC, blackcoder87 commented on application/modules/events/views/show/participation.php
>                                          <li style="width:25%;"><?=$this->getTrans('guest') ?></li>
Das "Inline Styling" können wir vielleicht durch Bootstrap 5-Klassen ersetzen.

2024-08-15 17:09 UTC, blackcoder87 commented on application/modules/events/models/Events.php
> +    protected $id = 0;
Gibt es eine id oder userId die 0 sein kann? Du wirst auch keine arithmetischen Operationen mit der id oder userId durchführen. Deswegen weiß ich nicht wieso diese zwingende Initialisierung mit irgendwelchen Werten.

Mit PHP 7.4 gibt es übrigens "Typed Properties" (Typisierte Eigenschaften):
https://www.php.net/manual/de/migration74.new-features.php

2024-08-15 17:15 UTC, hhunderter commented on application/modules/events/models/Events.php
> +    protected $id = 0;
Die Eigenschaften habe ich noch weggelassen weil diese auch noch nie in einem Modul verwendet wurde und das Modul laut Config auch noch unter 7,3 laufen würde.
Ich Gebe die ID den Anfangswert 0 weil bei einem Aufruf von getId() null stehen wurde und es zu einem Fehler kommt

2024-08-15 17:16 UTC, hhunderter commented on application/modules/events/views/show/participation.php
>                                          <li style="width:25%;"><?=$this->getTrans('guest') ?></li>
könnte man überlegen

2024-08-15 17:30 UTC, blackcoder87 commented on application/modules/events/models/Events.php
> +    protected $id = 0;
Ja, wenn man typisierte Eigenschaften nutzen würde, müsste man die Voraussetzung auf PHP 7.4 setzen. Ilch selber läuft ja seit letztens nur noch mit PHP 7.4 und neuer. Also kann man halt darüber nachdenken ob man typisierte Eigenschaften nutzt. Muss jetzt nicht für diesen PR.

> Ich Gebe die ID den Anfangswert 0 weil bei einem Aufruf von getId() null stehen wurde und es zu einem Fehler kommt
Das könnte aber auch eine falsche Denkweise sein. Jedenfalls ist ein Wert von 0 keine gültige ID. Wenn man ein Event aus der Datenbank holt und mit diesem im Form eines Event-Model weiterarbeitet, hat das Model ja die ID aus der Datenbank (die entsprechende Spalte der Tabelle). Es gibt eigentlich nur den Fall, dass es ein neues Event ist und es somit noch keine ID hat. Wenn das Event in der Datenbank abgelegt wird, bekommt es aber eine automatische ID.

Wenn du also im Modul darüber stolperst, dass getID() null ist, dann ist der Fehler im Modul. Man sollte wissen, ob man gerade mit einem neuen Event arbeitet (bisher noch ohne ID) oder mit einem aus der Datenbank, welches dann eine ID hat. ID = 0 wirst du in der Datenbank nicht finden.

2024-08-15 17:37 UTC, hhunderter commented on application/modules/events/models/Events.php
> +    protected $id = 0;
Ich mein ja nicht das ein Fehler im Modul ist (Ein anderer Entwickler kann dieses Model ja auch in andere Module verwenden), ich will nur ausschließen, das kein Fehler rausgegeben wird nur weil die id noch nicht initialisiert wurde und einen INT Wert erwartet ;)

2024-08-16 16:06 UTC, blackcoder87 requested changes

2024-08-16 16:06 UTC, blackcoder87 commented on application/modules/events/controllers/Index.php
> +            $eventMapper->delete($this->getRequest()->getParam('id', 0));
Wieso wissentlich unnötigerweise auf die Datenbank zugreifen?

2024-08-16 16:06 UTC, blackcoder87 commented on application/modules/events/controllers/Show.php
> +        $event = $eventMapper->getEventById($this->getRequest()->getParam('id', 0));
Wieso wissentlich unnötigerweise auf die Datenbank zugreifen?

2024-08-16 16:06 UTC, blackcoder87 commented on application/modules/events/controllers/Show.php
> +            $commentMapper->delete($this->getRequest()->getParam('id', 0));
Wieso wissentlich unnötigerweise auf die Datenbank zugreifen?

2024-08-16 16:06 UTC, blackcoder87 commented on application/modules/events/controllers/admin/Currency.php
> +            $currencyMapper->deleteCurrencyById($this->getRequest()->getParam('id', 0));
Wieso wissentlich unnötigerweise auf die Datenbank zugreifen?

2024-08-16 16:06 UTC, blackcoder87 commented on application/modules/events/controllers/admin/Index.php
> +            $eventMapper->delete($this->getRequest()->getParam('id', 0));
Wieso wissentlich unnötigerweise auf die Datenbank zugreifen?

2024-08-16 17:26 UTC, blackcoder87 commented on application/modules/events/translations/de.php
> +    'entryNotFound' => 'Eintag nicht gefunden.',
Hier war noch ein Tippfehler. "Eintag" ändern in "Eintrag".

2024-08-16 17:51 UTC, blackcoder87 submitted a review, later dismissed

2024-08-16 17:51 UTC, blackcoder87 commented on application/modules/events/views/index/treat.php
> +                        <option value="<?=$user->getId() ?>" <?php if (($event != '' && $event->getUserId() == $user->getId()) || $this->originalInput('creator') == $user->getId()) {
Vielleicht wieder `<?= () ? ... : '' ?>` ?

2024-08-16 17:51 UTC, blackcoder87 commented on application/modules/events/views/index/treat.php
> +                            echo date('d.m.Y H:i', strtotime($event->getStart()));
Wenn man das so behalten möchte, dann sieht die Einrückung aber komisch aus.

2024-08-16 17:51 UTC, blackcoder87 commented on application/modules/events/views/index/treat.php
> +                            echo date('d.m.Y H:i', strtotime($event->getEnd()));
Wie in Zeile 93.

2024-08-16 17:51 UTC, blackcoder87 commented on application/modules/events/views/index/treat.php
> +                    <option <?php if ($event != '' && $event->getPriceArt() == 0) {
Vielleicht wieder `<?= () ? ... : '' ?>` ?

2024-08-16 17:51 UTC, blackcoder87 commented on application/modules/events/views/index/treat.php
> +                    <option <?php if ($event != '' && $event->getPriceArt() == 0) {
Zeile 93?

"Reformat Code" oder "Reformat File" in PhpStorm ist nicht immer das gelbe vom Ei.

2024-08-16 17:51 UTC, blackcoder87 commented on application/modules/events/views/index/treat.php
> +                           <?php if (($event != '' && $event->getShow() == 1) || $this->originalInput('calendarShow') == 1) {
Vielleicht wieder `<?= () ? ... : '' ?>` ?

2024-08-16 18:02 UTC, hhunderter commented on application/modules/events/views/index/treat.php
> +                    <option <?php if ($event != '' && $event->getPriceArt() == 0) {
Das war noch nicht mal PHPStorm sondern der PHP CS-Fixer ;)
hab schon einiges wieder geändert aber sind doch noch welche unter gegangen

2024-08-24 09:43 UTC, merged