Downloads-Modul (1.14.1): PSR-fix
IlchCMS/Ilch-2.0 pull request #1036
Opened 2024-08-15 15:16 UTC by hhunderter

# Description
PSR fix

# This PR has been tested in the following browsers:
- [ ] Chrome
- [x] Firefox
- [ ] Opera
- [ ] Edge

2024-08-15 17:10 UTC, blackcoder87 commented on application/modules/downloads/models/DownloadsItem.php
> +    protected $id = 0;
Hier habe ich nur die Bemerkung, wie auch im anderen PR.

https://github.com/IlchCMS/Ilch-2.0/pull/1035#discussion_r1718724441

2024-08-15 17:18 UTC, hhunderter commented on application/modules/downloads/models/DownloadsItem.php
> +    protected $id = 0;
siehe Antwort in https://github.com/IlchCMS/Ilch-2.0/pull/1035#discussion_r1718724441

2024-08-24 07:49 UTC, blackcoder87 requested changes
Mit diesem Stand lässt sich keine Kategorie erstellen.

2024-08-24 07:56 UTC, blackcoder87 approved these changes

2024-08-24 07:57 UTC, merged