add Parameter to Date-Validators
IlchCMS/Ilch-2.0 pull request #495
Opened 2020-09-15 12:21 UTC by hhunderter

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# This PR has been tested in the following browsers:

- [ ] Chrome
- [X] Firefox
- [ ] Opera
- [ ] Edge
- [X] IE

2020-09-15 20:48 UTC, Mairu requested changes

2020-09-15 20:48 UTC, Mairu commented on application/libraries/Ilch/Validation.php
> +                $validator = str_replace('\\'.'\\', "\0\0\0_doub", $validator);
Why split '\\' . '\\' instead of using '\\\\'? (Same for '\\:')

2020-09-15 20:48 UTC, Mairu commented on application/libraries/Ilch/Validation/Validators/Date.php
> +        $this->setIsValid($d && $d->format($format) == $this->getValue());
=== should be used.

Also as there is a Unit Test for the Date validator, test cases should be added for usages of this introduced parameter.

2020-09-21 16:01 UTC, Mairu requested changes

2020-09-21 16:01 UTC, Mairu commented on tests/libraries/ilch/Validation/Validators/DateTest.php
>              ],
It would be nice to add test cases for usage of formats
- using a valid date with different format than Y-m-d
- using a valid date in Y-m-d with a different format, so that it should fail

2020-09-21 18:02 UTC, hhunderter commented on application/libraries/Ilch/Translations/de.php
> +    'validation.errors.date.mustBeDate' => '%s ist kein gültiges Datum oder flasches Format (%s).',
I give my best ;)

2020-09-21 19:48 UTC, merged