Teams update
IlchCMS/Ilch-2.0 pull request #652
Opened 2023-03-20 10:39 UTC by hhunderter

# Description

FontAwesome 6 #635
'Image'-Ordner fehlte

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# This PR has been tested in the following browsers:

- [ ] Chrome
- [x] Firefox
- [ ] Opera
- [ ] Edge
- [ ] IE

2023-03-20 14:31 UTC, blackcoder87 requested changes

2023-03-20 14:31 UTC, blackcoder87 commented on application/modules/teams/controllers/admin/Applications.php
> +                'icon' => 'fa-solid fa-th-list',
fa-th-list got renamed to fa-table-list

2023-03-20 14:31 UTC, blackcoder87 commented on application/modules/teams/controllers/admin/Applicationshistory.php
> +                'icon' => 'fa-solid fa-th-list',
fa-th-list got renamed to fa-table-list

2023-03-20 14:31 UTC, blackcoder87 commented on application/modules/teams/controllers/admin/Settings.php
> +                'icon' => 'fa-solid fa-th-list',
fa-th-list got renamed to fa-table-list

2023-03-24 16:13 UTC, blackcoder87 commented on application/modules/teams/models/Joins.php
> +    /**
Missing description.

2023-03-24 23:51 UTC, hhunderter commented on application/modules/teams/config/config.php
> +        return 'Update function executed.';
diese Ausgabe findet sich schon in so vielen Modulen und wenn sollte diese Funktion für alle gleich sein oder?
Eine Ausgabe könnte ich mir vorstellen, wenn es heißt die Rollback Funktion einzuführen

2023-03-25 00:02 UTC, hhunderter commented on application/modules/teams/controllers/Index.php
> -            if ($this->getUser()) {
Die Überprüfung ist nicht weg sie war nur doppelt, siehe Zeile 100

2023-03-25 04:45 UTC, blackcoder87 commented on application/modules/teams/config/config.php
> +        return 'Update function executed.';
This is the only occurrence I found:
https://github.com/IlchCMS/Ilch-2.0/blob/master/application/modules/admin/config/config.php#L883

2023-03-25 04:53 UTC, blackcoder87 approved these changes

2023-03-25 04:55 UTC, merged