Extension of the profile fields
IlchCMS/Ilch-2.0 pull request #663
Opened 2023-04-25 18:19 UTC by LordSchirmer

# Description

Extension and visual adjustments to the selection and display of profile fields.

New options:
- radio boxes
- check boxes,
- drop-down fields
- date fields

Fixes # (issue)

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# This PR has been tested in the following browsers:

- [X] Firefox

2023-04-26 14:16 UTC, blackcoder87 requested changes

2023-04-26 14:16 UTC, blackcoder87 commented on application/modules/user/views/profil/index.php
> +                        $value = implode(', ', unserialize($profileFieldContent->getValue()));
unserialize

2023-04-26 14:16 UTC, blackcoder87 commented on application/modules/user/views/panel/profile.php
> +                                $options = unserialize($profileField->getOptions());
unserialize

2023-04-26 14:18 UTC, blackcoder87 commented
Might be unrelated to your changes, but I am seeing these errors:

index.php/admin/user/profilefields/treat/id/11
> Trying to access array offset on value of type null in application/modules/user/views/admin/profilefields/treat.php:88
> Trying to access array offset on value of type null in application/modules/user/views/admin/profilefields/treat.php:94

2023-04-26 17:24 UTC, LordSchirmer commented on application/modules/user/models/ProfileField.php
> +     * @var text
Yes is a string. I will change it.

2023-04-26 17:25 UTC, LordSchirmer commented on application/modules/user/models/ProfileField.php
> +    public function setOptions($options)
Yes is a string. I will change it.

2023-04-26 17:27 UTC, LordSchirmer commented on application/modules/user/views/admin/index/treatProfile.php
> +                $value = implode(', ', unserialize($profileFieldContent->getValue()));
Ok I did not know. I will take a look.

2023-04-26 17:34 UTC, LordSchirmer commented on application/modules/user/views/admin/profilefields/treat.php
> +    var iconArray = ['fa-regular fa-square','fa fa-list','fa-regular fa-face-smile','fa-regular fa-circle-check','fa-regular fa-square-check','far fa-caret-square-down','fa-regular fa-calendar-days']
I will change

2023-04-27 13:47 UTC, blackcoder87 requested changes

2023-04-27 13:47 UTC, blackcoder87 commented on application/modules/user/views/admin/profilefields/treat.php
> +                    <?=($optionsAnz == 1) ? $this->getTrans('profileFieldOptions') : ''; $optionsAnz++; ?>
You initialize $optionsAnz with 1 and check here if it is 1. Can this ever have a different value than 1?
Doesn't look like it is inside a loop.

2023-04-27 16:02 UTC, LordSchirmer commented on application/modules/user/views/admin/profilefields/treat.php
> +                    <?=($optionsAnz == 1) ? $this->getTrans('profileFieldOptions') : ''; $optionsAnz++; ?>
The goal was to only put the word "choice" once in front of the input fields. For me this was the only possibility in connection with the dynamic fields. Not nice but the goal reached :)

2023-04-27 17:31 UTC, blackcoder87 commented on application/modules/user/views/admin/profilefields/treat.php
> +                    <?=($optionsAnz == 1) ? $this->getTrans('profileFieldOptions') : ''; $optionsAnz++; ?>
I removed that workaround and don't see it being repeated. Can you confirm that?

2023-04-28 07:18 UTC, LordSchirmer commented on application/modules/user/views/admin/profilefields/treat.php
> +                    <?=($optionsAnz == 1) ? $this->getTrans('profileFieldOptions') : ''; $optionsAnz++; ?>
The test showed no errors. Nice work! Thanks for your adjustments.

2023-04-28 12:08 UTC, blackcoder87 approved these changes

2023-04-28 12:11 UTC, merged