Update GalleryModule
IlchCMS/Ilch-2.0 pull request #767
Opened 2023-09-03 07:25 UTC by RTX2070

Moin Moin,

nochmals der PR bzgl. GalleryModule (Venobox)
Folgende Einstellungen sind nun im Module möglich.

- Nummerierung
- Hintergrundfarbe
- Unendliche Gallery
- Farbe vom Rahmen
- Stärke vom Rahmen
- Bildtitel anzeigen

2023-09-03 08:57 UTC, blackcoder87 requested changes

2023-09-03 08:57 UTC, blackcoder87 commented on application/modules/gallery/controllers/Index.php
> +
Empty lines not needed.

2023-09-03 08:57 UTC, blackcoder87 commented on application/modules/gallery/controllers/admin/Settings.php
> +                $pictureOfXSource = is_array($data = $this->getRequest()->getPost('pictureOfXSource')) ? implode(",", $data) : '';
https://github.com/IlchCMS/Ilch-2.0/pull/739/files#r1299163816

2023-09-03 08:57 UTC, blackcoder87 commented on application/modules/gallery/controllers/admin/Settings.php
> +        $this->getView()->set('pictureOfXSource', explode(',', $this->getConfig()->get('gallery_pictureOfXSource')));
https://github.com/IlchCMS/Ilch-2.0/pull/739/files#r1299163824

2023-09-03 08:57 UTC, blackcoder87 commented on application/modules/gallery/translations/de.php
> +    'venoboxInfinigall' => 'Unendliche Gallery?',
Not really needed to cut down the names.. For example you could have just wrote
venoboxInfiniteGallery

2023-09-03 08:57 UTC, blackcoder87 commented on application/modules/gallery/views/admin/settings/index.php
> +    <h1>Venobox Einstellungen</h1>
Missing translation

2023-09-03 08:57 UTC, blackcoder87 commented on application/modules/gallery/views/admin/settings/index.php
> +            <div class="form-text">Zum Beispiel: 15px</div>
Missing translation

2023-09-03 08:57 UTC, blackcoder87 commented on application/modules/gallery/translations/en.php
> +    'venoboxOverlayColor' => 'Background Color?',
Wrong use of capital and small initial letters

2023-09-03 08:57 UTC, blackcoder87 commented on application/modules/gallery/config/config.php
> +        'version' => '1.21.2',
New features.. so you could update the version number to 1.22.0.

2023-09-03 11:26 UTC, RTX2070 commented on application/modules/gallery/translations/en.php
> +    'venoboxOverlayColor' => 'Background Color?',
Wie meinst du das?

2023-09-03 11:27 UTC, RTX2070 commented on application/modules/gallery/translations/de.php
> +    'venoboxInfinigall' => 'Unendliche Gallery?',
Könnte aber so bleiben oder soll ich ändern?

2023-09-03 11:28 UTC, RTX2070 commented on application/modules/gallery/controllers/admin/Settings.php
> +                $pictureOfXSource = is_array($data = $this->getRequest()->getPost('pictureOfXSource')) ? implode(",", $data) : '';
Habe meinen alten PR gar nicht wieder verwendet sondern alles neu gemacht

2023-09-03 16:33 UTC, RTX2070 commented on application/modules/gallery/controllers/Index.php
> +
erledigt

2023-09-03 16:33 UTC, RTX2070 commented on application/modules/gallery/controllers/admin/Settings.php
> +                $pictureOfXSource = is_array($data = $this->getRequest()->getPost('pictureOfXSource')) ? implode(",", $data) : '';
erledigt

2023-09-03 16:33 UTC, RTX2070 commented on application/modules/gallery/controllers/admin/Settings.php
> +        $this->getView()->set('pictureOfXSource', explode(',', $this->getConfig()->get('gallery_pictureOfXSource')));
erledigt

2023-09-03 16:33 UTC, RTX2070 commented on application/modules/gallery/translations/de.php
> +    'venoboxInfinigall' => 'Unendliche Gallery?',
erledigt

2023-09-03 16:34 UTC, RTX2070 commented on application/modules/gallery/views/admin/settings/index.php
> +    <h1>Venobox Einstellungen</h1>
erledigt

2023-09-03 16:34 UTC, RTX2070 commented on application/modules/gallery/views/admin/settings/index.php
> +            <div class="form-text">Zum Beispiel: 15px</div>
erledigt

2023-09-03 16:34 UTC, RTX2070 commented on application/modules/gallery/config/config.php
> +        'version' => '1.21.2',
erledigt

2023-09-03 16:34 UTC, RTX2070 commented on application/modules/gallery/translations/en.php
> +    'venoboxOverlayColor' => 'Background Color?',
erledigt

2023-09-03 18:26 UTC, blackcoder87 requested changes

2023-09-03 18:26 UTC, blackcoder87 commented on application/modules/gallery/translations/en.php
> +    'venoboxOverlayColor' => 'Background Color?',
Ist nicht erledigt.

2023-09-03 18:26 UTC, blackcoder87 commented on application/modules/gallery/translations/de.php
> +    'for example: 15px' => 'zum Beispiel: 15px',
Not a proper key..

2023-09-03 18:26 UTC, blackcoder87 commented on application/modules/gallery/translations/en.php
> +    'venoboxSetting' => 'Venobox Settings'
'for example: 15px' where?

2023-09-03 18:26 UTC, blackcoder87 commented on application/modules/gallery/translations/de.php
> +    'venoboxInfinigall' => 'Unendliche Gallery?',
Ist nicht erledigt.

2023-09-03 18:36 UTC, RTX2070 commented
Wie soll es denn deiner Meinung nach aussehen?

2023-09-03 18:47 UTC, RTX2070 commented on application/modules/gallery/translations/de.php
> +    'venoboxInfinigall' => 'Unendliche Gallery?',
Was genau meinst du damit?

2023-09-03 18:48 UTC, RTX2070 commented on application/modules/gallery/translations/en.php
> +    'venoboxOverlayColor' => 'Background Color?',
Ist doch geschrieben wie die anderen Keys auch

2023-09-03 18:49 UTC, RTX2070 commented on application/modules/gallery/translations/de.php
> +    'for example: 15px' => 'zum Beispiel: 15px',
Was wäre ein passender Key?

2023-09-03 18:52 UTC, blackcoder87 commented on application/modules/gallery/translations/de.php
> +    'venoboxInfinigall' => 'Unendliche Gallery?',
Keine unnötigen Abkürzungen. Anstatt "venoboxInfinigall" hätte man auch "venoboxInfiniteGallery" schreiben können.
War kein wichtiger Punkt für mich, aber wenn du einfach behauptest es wäre erledigt, dann ist es wichtig.

2023-09-03 18:54 UTC, blackcoder87 commented on application/modules/gallery/translations/en.php
> +    'venoboxOverlayColor' => 'Background Color?',
Hier meine ich nicht den Key, sondern generell die Groß- und Kleinschreibung im Englischen.
'Background color?'
'Numbering of image?'
'Backgroundcolor of image?'
usw.

2023-09-03 18:54 UTC, blackcoder87 commented on application/modules/gallery/translations/de.php
> +    'for example: 15px' => 'zum Beispiel: 15px',
Wie die anderen auch. Keine Leerzeichen usw.

Die anderen sind alle wie "venoboxSetting" und auf einmal "for example: 15px"?

2023-09-03 19:04 UTC, RTX2070 commented on application/modules/gallery/translations/de.php
> +    'venoboxInfinigall' => 'Unendliche Gallery?',
Alles klar... strenger Lehrer ;)

2023-09-03 19:05 UTC, RTX2070 commented on application/modules/gallery/translations/en.php
> +    'venoboxOverlayColor' => 'Background Color?',
Jetzt verstehe ich was du meinst

2023-09-03 19:06 UTC, RTX2070 commented on application/modules/gallery/translations/de.php
> +    'for example: 15px' => 'zum Beispiel: 15px',
Okay

2023-09-05 16:08 UTC, blackcoder87 approved these changes

2023-09-05 16:16 UTC, merged