Gallery
IlchCMS/Ilch-2.0 pull request #770
Opened 2023-09-06 11:14 UTC by hhunderter

# Description

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# This PR has been tested in the following browsers:

- [ ] Chrome
- [x] Firefox
- [ ] Opera
- [ ] Edge

2023-09-06 14:49 UTC, RTX2070 requested changes

2023-09-06 14:49 UTC, RTX2070 commented on application/modules/gallery/config/config.php
> +            ->set('gallery_venoboxBorder', 0)
Sollte hier nicht lieber auch String sein ? Die Option für venobox benötigt Angabe mit px also bspw. 10px.
Entweder String oder int aber bei int müsste die View dann auch noch abgeändert werden

2023-09-06 15:14 UTC, RTX2070 commented on application/modules/gallery/config/config.php
> +            ->set('gallery_venoboxBorder', 0)
Bei Border meine ich

2023-09-06 15:23 UTC, RTX2070 reviewed
Bei ShowImage hatte ich die Venobox übrigens entfernt... könnte man aber wieder einbauen wegen der Box

2023-09-06 18:19 UTC, RTX2070 approved these changes

2023-09-06 18:43 UTC, hhunderter commented on application/modules/gallery/config/config.php
> +            ->set('gallery_venoboxBorder', 0)
Ja hast recht werde ich abändern

2023-09-06 18:44 UTC, hhunderter commented on application/modules/gallery/config/config.php
> +            case "1.21.1":
1.22.0 ist die aktuellste Version es wird dort immer die letzte Version übergeben also so richtig

2023-09-06 18:45 UTC, hhunderter commented on application/modules/gallery/views/admin/settings/index.php
> +                   value="<?=$this->escape($this->originalInput('venoboxBorder', $this->get('venoboxBorder'))) ?>" />
Siehe oben... aber ätsch hast du auch vergessen gehabt ;)

2023-09-06 18:50 UTC, hhunderter commented
> Bei ShowImage hatte ich die Venobox übrigens entfernt... könnte man aber wieder einbauen wegen der Box

Du hattest ja einen Grund gehabt das zu entfernen,  ich weiß jetzt nicht was für vor oder Nachteile dadurch entstehen

2023-09-07 03:54 UTC, RTX2070 commented on application/modules/gallery/config/config.php
> +            ->set('gallery_venoboxBorder', 0)
Ok

2023-09-07 03:54 UTC, RTX2070 commented on application/modules/gallery/config/config.php
> +            case "1.21.1":
Achso..OK.

2023-09-07 03:54 UTC, RTX2070 commented on application/modules/gallery/views/admin/settings/index.php
> +                   value="<?=$this->escape($this->originalInput('venoboxBorder', $this->get('venoboxBorder'))) ?>" />
Stimmt ;)

2023-09-11 06:26 UTC, hhunderter commented
Noch irgendwelche Einwände?
ansonsten könnte es mit rein....

2023-09-11 10:22 UTC, merged