Update getMenu() sowie Anpassung des Tests
IlchCMS/Ilch-2.0 pull request #778
Opened 2023-09-22 10:02 UTC by RTX2070

1. Options-Array erweitert um `<span>` Tag.
2. ContentString angepasst für bessere Lesbarkeit.
3. Link-Titel wird in ein `<span>` verschachtelt (aber nur wenn eine Klasse angegeben wurde) -> **If-Abfrage**
4. **Tests:** -> GetMenuTest.php angepasst für Änderungen.

2023-09-22 12:44 UTC, blackcoder87 requested changes

2023-09-22 12:44 UTC, blackcoder87 commented on application/modules/faq/views/admin/cats/index.php
> +<<<<<<< HEAD
merge conflict

2023-09-22 12:44 UTC, blackcoder87 commented on application/libraries/Ilch/Layout/Helper/Menu/Model.php
> +                // Span Klassen
Comment is in german.

2023-09-22 12:47 UTC, blackcoder87 commented on application/libraries/Ilch/Layout/Helper/Menu/Model.php
> +                    $title = $this->layout->escape($menuData['items'][$itemId]->getTitle());
Spread a single line of string concatenation for building an hyperlink over several lines? Improvement?

2023-09-22 12:47 UTC, blackcoder87 commented
Kannst du noch genauer erklären was die Änderung bewirken soll bzw. wofür die sein soll?
Wofür wird das genau gebraucht?

2023-09-22 18:02 UTC, RTX2070 commented on application/modules/faq/views/admin/cats/index.php
> +<<<<<<< HEAD
Ja...das war der Mist, was ich meinte

2023-09-22 18:05 UTC, RTX2070 commented
> Kannst du noch genauer erklären was die Änderung bewirken soll bzw. wofür die sein soll? Wofür wird das genau gebraucht?

Erweitert die Ausgabe im Menü um ein Span Tag.
Viele Bootstrap navbars nutzen Span Tags gerade in Bezug auf Bootstrap 5

2023-09-22 18:06 UTC, RTX2070 commented on application/libraries/Ilch/Layout/Helper/Menu/Model.php
> +                    $title = $this->layout->escape($menuData['items'][$itemId]->getTitle());
Finde die Lesbarkeit so besser als einzeilig

2023-09-23 06:12 UTC, RTX2070 reviewed
So sollte es jetzt passen oder?

2023-09-23 07:56 UTC, blackcoder87 commented on application/modules/faq/views/admin/cats/index.php
> +<<<<<<< HEAD
Du hättest nachdem du deine Arbeit am FAQ-Modul abgeschlossen hattest deinen Fork auf den aktuellen Stand vom master bringen müssen. Also bevor du etwas neues anfängst immer den master auf den aktuellen Stand bringen.

2023-09-25 12:57 UTC, blackcoder87 approved these changes

2023-09-25 12:58 UTC, merged