Update forum, shop,  pagination,   article,  history
IlchCMS/Ilch-2.0 pull request #803
Opened 2023-10-05 13:30 UTC by Slipi85

# Description

Update Forum front and fixed admin
Fixed Shop show.php indicators
Update pagination.php
Fixed Article index
Fixed History

2023-10-05 13:55 UTC, Slipi85 commented
Werde ab jetzt alle Module nochmals Controlieren und mit der BS3 version vergleichen. 
Ich habe bis jetzt nur die Standart Module bearbeitet, werde dan alle Ilch module installieren und diese bearbeiten.

Im Forum habe ich die .btn alls mit .btn-sm bearbeitet, da die normale größe zu groß ist. 

Im Shop show.php habe ich den slider im Modal bearbeitet, nochmals sry das ich vor dem PR nicht kontroliert habe.

2023-10-06 11:52 UTC, blackcoder87 requested changes

2023-10-06 11:52 UTC, blackcoder87 commented on application/modules/forum/static/css/forum.css
Können die auskommentierten Zeilen weg?

2023-10-06 12:04 UTC, blackcoder87 commented
@Slipi85 
Bitte die kommentierten Punkte in den jeweiligen PR abarbeiten und nicht mit dem nächsten PR.
Wenn du den PR zurückziehen willst, musst du ihn schließen.

Ich habe jetzt die anderen beiden PR gemerged, nachdem ich die Merge-Konflikte behoben und den ganzen Kram entfernt habe, der nicht in den PR gehörte. Bitte deinen Fork auf den aktuellen Stand bringen und dann deine lokalen Dateien, an denen du arbeitest. Das schließt auch die composer-Dateien mit ein. Erst danach neue Arbeiten anfangen.

2023-10-06 12:49 UTC, Slipi85 commented
Da ich mich wenig mit GitHub beschäftige, war es mir nicht bewusst, das ich PR nachträglich bearbeiten. 
Um eine PR abzuarbeiten müßte ich was tun? möchte nichts falschen tun.

Also nächster PR wenn der jetzige abgearbeitet wurde?

2023-10-06 12:50 UTC, Slipi85 commented on application/modules/forum/static/css/forum.css
Ja, ich hatte es vergessen dies zu tun. Kann ich dies bei der abarbeitung des PR erledigen.

2023-10-06 12:57 UTC, blackcoder87 commented on application/modules/forum/static/css/forum.css
Ja, unterm PR steht:

> Add more commits by pushing to the [Update-Form---Shop---pagination---article--history---war](https://github.com/Slipi85/Ilch-2.0.bs.531/tree/Update-Form---Shop---pagination---article--history---war) branch on [Slipi85/Ilch-2.0.bs.531](https://github.com/Slipi85/Ilch-2.0.bs.531).

Du kannst also die entsprechende Datei bearbeiten und dann die Änderungen an der Datei committen.

2023-10-06 13:00 UTC, blackcoder87 commented
> Also nächster PR wenn der jetzige abgearbeitet wurde?

Ja, wenn dieser gemerged ist, sind die Änderungen im UpdateToBootstrap5-Branch. Dann kannst du deinen Fork synchronisieren, damit der Branch bei dir auch auf diesem Stand ist. Weiteres steht in der Anleitung, die ich dir geschickt hatte.

2023-10-07 12:04 UTC, blackcoder87 approved these changes

2023-10-07 12:05 UTC, merged