Fixed finish event vote layout war media iframe
IlchCMS/Ilch-2.0 pull request #839
Opened 2023-10-28 09:58 UTC by Slipi85

# Description
Fixed Modul Media iframe
Fixed Layout clan3columns
Fixed Events
Fixed Vote
Fixed Training

Sollte es keine änderungen mehr geben oder benödigt werden, wäre es das vor letzte PR für das System und deren Module und Layout, da das Plug-in für BS5 calender noch austehend ist.

Module Dritte und Layout benödige ich rechte um diese zu bearbeiten.

Ich bitte euch alle das System zu teste, mehr paar augen sehen mehr als nur ein paar.

2023-10-28 11:19 UTC, blackcoder87 requested changes

2023-10-28 11:19 UTC, blackcoder87 commented on application/modules/events/views/show/event.php
> +                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
Translation for aria-label is missing. Previously used "&times;" is missing.

2023-10-28 11:19 UTC, blackcoder87 commented on application/layouts/clan3columns/index.php
> +          <nav class="navbar navbar-expand-lg navbar-dark navbar-gaming bg-dark fixed-top d-sm-block d-md-none">
![navbar-dark](https://github.com/IlchCMS/Ilch-2.0/assets/18415497/4b8294eb-eb91-4a3d-9e68-9677a858c824)

@hhunderter 
Another opinion needed for that change.

2023-10-28 16:45 UTC, Slipi85 commented on application/modules/events/views/show/event.php
> +                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
btn-close erzeugt das X . btn-close ist eine neue Bootstrap klasse. Übersetzung kann ich unter translation hinzufügen.

2023-10-28 16:49 UTC, Slipi85 commented on application/layouts/clan3columns/index.php
> +          <nav class="navbar navbar-expand-lg navbar-dark navbar-gaming bg-dark fixed-top d-sm-block d-md-none">
bg-dark wurde gewählt, da dass jetzige standart Layout ebenfalls einen dunklen Background hat. Ich finde bg-light angenehmner, da das Layout generell hell ist.

2023-10-28 17:09 UTC, hhunderter commented on application/layouts/clan3columns/index.php
> +          <nav class="navbar navbar-expand-lg navbar-dark navbar-gaming bg-dark fixed-top d-sm-block d-md-none">
Ist eine sehr gute Frage.
Ich bin auch immer der Meinung alles so gut wie möglich 1zu1 umzuändern.

2023-10-29 04:16 UTC, blackcoder87 approved these changes

2023-10-29 04:19 UTC, merged